name: ci

on:
  push:
    branches: [master]
  pull_request:

env:
  NIX_CONFIG: experimental-features = nix-command flakes

jobs:
  test:
    runs-on: codeberg-tiny
    steps:
      - uses: https://code.forgejo.org/actions/checkout@v4

      - uses: https://github.com/astral-sh/setup-uv@v6
        with:
          python-version: "3.13"

      - name: lint
        run: uvx ruff check .

      - name: test
        run: uv run pytest

  format:
    runs-on: codeberg-small
    container:
      image: nixos/nix:latest
    steps:
      - run: |
          git clone "${{ github.server_url }}/${{ github.repository }}.git" .
          git checkout "${{ github.sha }}"
      - run: nix run --inputs-from . nixpkgs#alejandra -- --check .

  flake-check:
    runs-on: codeberg-medium
    container:
      image: nixos/nix:latest
    steps:
      - run: |
          git clone "${{ github.server_url }}/${{ github.repository }}.git" .
          git checkout "${{ github.sha }}"
      - run: nix flake check
